export const BASE_API_URI = '/api'
export const RESTAURANTS_URI = BASE_API_URI + '/restaurants'
export const MENU_URI = BASE_API_URI + '/menus'
export const MENU_DOCUMENTS_URI = BASE_API_URI + '/menu_documents'
export const USERS_MENU_URI = BASE_API_URI + '/userDayMenus'
